#!/usr/bin/env python
# -*- coding: utf-8 -*-
import vk
import os
import sys,getopt
from time import localtime, strftime
from random import randint
from time import sleep
import webbrowser
import json
access_token="YOUR_ACCES_TOKEN"
session = vk.Session(access_token=access_token)
vkapi = vk.API(session)
repsonse = vkapi.messages.get(count=1)
print(repsonse[1]["body"])
print(repsonse[1]["read_state"])